export {default as Header} from './header'
export {default as Hero } from './hero'
export {default as About} from './about'
export {default as About2} from './about2'
export {default as Popular} from './popular'
export {default as Choos} from './choos'
export {default as Testimonials} from './testimonials'
export {default as SubscribeSection} from './subscribeSection'
export {default as Footer} from './footer'